import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { ContextProvider } from "../contexts/ContextProvider";
import TransactionSigner from "../components/TransactionSigner";
import {
  WalletDisconnectButton,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import { NetworkSwitcher } from "../components/NetworkSwitcher";

// Default styles that can be overridden by your app
require("@solana/wallet-adapter-react-ui/styles.css");

const WalletDisconnectButtonDynamic = dynamic(
  async () =>
    (await import("@solana/wallet-adapter-react-ui")).WalletDisconnectButton,
  { ssr: false }
);
const WalletMultiButtonDynamic = dynamic(
  async () =>
    (await import("@solana/wallet-adapter-react-ui")).WalletMultiButton,
  { ssr: false }
);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContextProvider>
        <div className="row">
          <div className="col-12 col-lg-6">
            <div className={styles.walletButtons}>
              <WalletMultiButtonDynamic />
              <WalletDisconnectButtonDynamic />
            </div>
          </div>
          <div className="col-12 col-lg-6">
            <div className={styles.walletButtons}>
              <NetworkSwitcher />
            </div>
          </div>
        </div>
        <TransactionSigner />
      </ContextProvider>
      <main className={styles.main}></main>
    </div>
  );
};

export default Home;
